## Documentation: http://docs.travis-ci.com/user/languages/python/
language: python
os:
  - linux
  # - osx

python:
  - 3.7
  - nightly

notifications:
  email: false
git:
  depth: 99999999

# matrix:
#   allow_failures:
#   - julia: nightly

# before_install:
#   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi

# install: pip install tox tox-travis
# script: tox
